version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=growthspree
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=growthspree
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"

  frontend:
    build:
      context: ./frontend/user-auth
    working_dir: /app
    command: npm start
    volumes:
      - ./frontend/user-auth:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

volumes:
  postgres_data:
